# Generated by Django 2.2.6 on 2019-10-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sith', '0002_auto_20191025_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sith',
            options={'verbose_name_plural': 'sith'},
        ),
        migrations.AlterField(
            model_name='recruit',
            name='assigned_sith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sith.Sith'),
        ),
    ]
